#include "typedefs.h"
#include <stdio.h>
#include <string.h>

#include "common.h"
#include "system.h"
#include "time_server.h"
#include "interrupt_server.h"
//#include "key_server.h"

#include "gpio_defs.h"
#include "led.h"
//#include "lcd12864.h"
//#include "buzzer.h"

#include "radio.h"
#include "uart.h"

/*******************************************************
;---------------------------------------
;  CMT2219B Configuration File
;  Generated by CMOSTEK RFPDK_V1.59
;  2025.11.02 15:01
;---------------------------------------
; Mode                    = Advanced
; Part Number             = CMT2219B
; Frequency               = 433.920 MHz
; Xtal Frequency          = 26.0000 MHz
; Demodulation            = FSK
; AGC                     = On
; Data Rate               = 9.6 kbps
; Deviation               = 20.0 kHz
; Rx Xtal Tol.            = 20 ppm
; Bandwidth               = Auto-Select kHz
; CDR Type                = Manchester
; CDR DR Range            = NA
; AFC                     = On
; AFC Method              = Auto-Select
; Data Representation     = 0:F-low 1:F-high
; Rx Duty-Cycle           = Off
; Sleep Timer             = Off
; Sleep Time              = NA
; Rx Timer                = Off
; Rx Time T1              = NA
; Rx Time T2              = NA
; Rx Exit State           = SLEEP
; SLP Mode                = Disable
; RSSI Valid Source       = PJD
; PJD Window              = 8 Jumps
; LFOSC Calibration       = On
; Xtal Stable Time        = 2480 us
; RSSI Compare TH         = NA
; Data Mode               = Packet
; Whitening               = Disable
; Whiten Type             = NA
; Whiten Seed Type        = NA
; Whiten Seed             = NA
; Manchester              = Enable
; Manchester Type         = 10=One, 01=Zero
; FEC                     = Disable
; FEC Type                = NA
; Packet Type             = Fixed Length
; Node-Length Position    = NA
; Payload Bit Order       = Start from msb
; Preamble Rx Size        = 0
; Preamble Value          = 0
; Preamble Unit           = 8-bit
; Sync Size               = 2-byte
; Sync Value              = 1
; Sync Tolerance          = None
; Sync Manchester         = Enable
; Node ID Size            = NA
; Node ID Value           = NA
; Node ID Mode            = None
; Node ID Err Mask        = Disable
; Node ID Free            = Disable
; Payload Length          = 10
; CRC Options             = None
; CRC Seed                = NA
; CRC Range               = NA
; CRC Swap                = NA
; CRC Bit Invert          = NA
; CRC Bit Order           = NA
; Dout Mute               = Off
; Dout Adjust Mode        = Disable
; Dout Adjust Percentage  = NA
; Collision Detect        = Off
; Collision Detect Offset = NA
; RSSI Detect Mode        = Always
; RSSI Filter Setting     = No Filtering
; RF Performance          = High
; LBD Threshold           = 2.4 V
; RSSI Offset             = 26
; RSSI Offset Sign        = 1

*********************************************************/

#define RF_RX_TIMEOUT    1000*60*60      //60min
#define RF_PACKET_SIZE   10             /* Define the payload size here */
#define TEST_DBG	false
	
static u8 g_rxBuffer[RF_PACKET_SIZE];   /* RF Rx buffer */
//static u8 g_txBuffer[RF_PACKET_SIZE];   /* RF Tx buffer */

char str[100];

uint32_t g_nRecvCount=0,g_nSendCount=0;

//rfpacket *tpms_pckt=(rfpacket*)&g_rxBuffer[0];
new_rfpacket *tpms_pckt=(new_rfpacket*)&g_rxBuffer[0];

//float batt_v,prsure_kPa;

//int8_t temp_centigrt;

u8 tpms_data_rdy=0;

#if (TEST_DBG)
RCC_ClocksTypeDef RCC_Clocks;
#endif
void Mcu_Init(void)
{
    /* system init */
    SystemInit();
		//SystemCoreClockUpdate();
    GPIO_Config();
    NVIC_Config();
    SystemTimerDelay_Config();
  	ADC1_Init();
    Timer5_Config();
	Timer7_Config();
	Timer3_Config();

//printf("SYSCLK Frequency: %lu Hz\n", RCC_Clocks.SYSCLK_Frequency);
//printf("HCLK Frequency: %lu Hz\n", RCC_Clocks.HCLK_Frequency);
//printf("PCLK1 Frequency: %lu Hz\n", RCC_Clocks.PCLK1_Frequency);
//printf("PCLK2 Frequency: %lu Hz\n", RCC_Clocks.PCLK2_Frequency);

//    lcd12864_init();
//    buzzer_init();
//    
//    lcd12864_led_on();
}

u8 Radio_Recv_FixedLen(u8 pBuf[],u8 len)
{
	if(CMT2300A_ReadGpio2())  /* Read INT2, PKT_DONE */	
	{
//      if(CMT2300A_MASK_PKT_OK_FLG & CMT2300A_ReadReg(CMT2300A_CUS_INT_FLAG))  /* Read PKT_OK flag */
//	{
		CMT2300A_GoStby();
		CMT2300A_ReadFifo(pBuf,len);
		CMT2300A_ClearRxFifo();
		CMT2300A_ClearInterruptFlags();
		CMT2300A_GoRx();
		return 1;
//	}
	}
return 0;
}

/* Main application entry point */
int main(void) //
{
    Mcu_Init();
    RF_Init();
	USART3_Init();
	#if (TEST_DBG)
	USART3_SendString("hello test");
	//test_outputs();//test pe9-pe12
	RCC_GetClocksFreq(&RCC_Clocks);
	#endif
	  if(FALSE==CMT2300A_IsExist()) {
        views_print_line(0, "CMT2300A not found!");
        while(1);
    }
    else {
        views_print_line(0, "CMT2300A ready RX");
    }
	
	  CMT2300A_GoStby();
	
	/* Must clear FIFO after enable SPI to read or write the FIFO */
  CMT2300A_EnableReadFifo();
	CMT2300A_ClearInterruptFlags();
	CMT2300A_ClearRxFifo();
  CMT2300A_GoRx();
	
	while(1)
	{
		if(!READ_GPIO_PIN(micro_sw2_GPIO))
		{	
			system_delay_ms(200);
		
			if (!READ_GPIO_PIN(micro_sw1_GPIO))
			{
				output_on(valve_3);
				champer_state=champer_close;
				//req_state=idl;
			}
		}
		if(Radio_Recv_FixedLen(g_rxBuffer,RF_PACKET_SIZE))
		{
			g_nRfRxtimeoutCount=0;
			g_nRecvCount++;
			u8 crc=crc8_calc(g_rxBuffer,RF_PACKET_SIZE-1);
			if(crc==g_rxBuffer[RF_PACKET_SIZE-1])
			{
				if(((tpms_pckt->prdct_id>>3)& 0x1F) == new_custumer_id)
				{
   					tpms_pckt->tempreture=tpms_pckt->tempreture-1-49;
//					tpms_pckt->prsur=
//					u32 tpms_id=tpms_pckt->ID;
//					u32 tpms_id_chpk=0;
//					tpms_id_chpk=(tpms_id&0xff)<<24|((tpms_id>>8 &0xff)<<16)|((tpms_id>>16 &0xff)<<8)|((tpms_id>>24 &0xff));//msb  first
//					tpms_pckt->ID=tpms_id_chpk;
					tpms_data_rdy=1;
                                              					
				}
			}
//			for(u8 i=0;i<RF_PACKET_SIZE;i++) //Clear Buff
//			g_rxBuffer[i]=0;
				 
		}

       if(g_nRfRxtimeoutCount>RF_RX_TIMEOUT) //Time Out
			 {
				  g_nRfRxtimeoutCount=0;
					CMT2300A_GoSleep();
					CMT2300A_GoStby();
					CMT2300A_ClearInterruptFlags();
					CMT2300A_ClearRxFifo();
					CMT2300A_GoRx();
			 }	
			if(int_flg)
			{
				int_flg=0;
				handle_cmd();
				read_prs_sensor();
			}
	}		
}
